export const provinceOptions = [
  { label: 'All regions', value: 'All regions' },
  { label: 'Aceh', value: 'Aceh' },
  { label: 'Bali', value: 'Bali' },
  { label: 'Bangka Belitung Islands', value: 'Bangka Belitung Islands' },
  { label: 'Banten', value: 'Banten' },
  { label: 'Bengkulu', value: 'Bengkulu' },
  { label: 'Central Java', value: 'Central Java' },
  { label: 'Central Kalimantan', value: 'Central Kalimantan' },
  { label: 'Central Sulawesi', value: 'Central Sulawesi' },
  { label: 'East Java', value: 'East Java' },
  { label: 'East Kalimantan', value: 'East Kalimantan' },
  { label: 'East Nusa Tenggara', value: 'East Nusa Tenggara' },
  { label: 'Gorontalo', value: 'Gorontalo' },
  { label: 'Jakarta', value: 'Jakarta' },
  { label: 'Jambi', value: 'Jambi' },
  { label: 'Lampung', value: 'Lampung' },
  { label: 'Maluku', value: 'Maluku' },
  { label: 'North Kalimantan', value: 'North Kalimantan' },
  { label: 'North Maluku', value: 'North Maluku' },
  { label: 'North Sulawesi', value: 'North Sulawesi' },
  { label: 'North Sumatra', value: 'North Sumatra' },
  { label: 'Papua', value: 'Papua' },
  { label: 'Riau', value: 'Riau' },
  { label: 'Riau Islands', value: 'Riau Islands' },
  { label: 'Southeast Sulawesi', value: 'Southeast Sulawesi' },
  { label: 'South Kalimantan', value: 'South Kalimantan' },
  { label: 'South Sulawesi', value: 'South Sulawesi' },
  { label: 'South Sumatra', value: 'South Sumatra' },
  { label: 'West Java', value: 'West Java' },
  { label: 'West Kalimantan', value: 'West Kalimantan' },
  { label: 'West Nusa Tenggara', value: 'West Nusa Tenggara' },
  { label: 'West Papua', value: 'West Papua' },
  { label: 'West Sulawesi', value: 'West Sulawesi' },
  { label: 'West Sumatra', value: 'West Sumatra' },
  { label: 'Special Region of Yogyakarta', value: 'Special Region of Yogyakarta' },
  { label: 'Highland Papua', value: 'Highland Papua' },
  { label: 'Southwest Papua', value: 'Southwest Papua' },
  { label: 'Central Papua', value: 'Central Papua' }
];