export const provinceOptions = [
  { label: 'All regions', value: 'All regions' },
  { label: 'Aceh', value: 'Aceh' },
  { label: 'Bali', value: 'Bali' },
  { label: 'Bangka Belitung Islands', value: 'Bangka Belitung Islands' },
  { label: 'Banten', value: 'Banten' },
  { label: 'Bengkulu', value: 'Bengkulu' },
  { label: 'Central Java', value: 'Central Java' },
  { label: 'Central Kalimantan', value: 'Central Kalimantan' },
  { label: 'Central Sulawesi', value: 'Central Sulawesi' },
  { label: 'East Java', value: 'East Java' },
  { label: 'East Kalimantan', value: 'East Kalimantan' },
  { label: 'East Nusa Tenggara', value: 'East Nusa Tenggara' },
  { label: 'Gorontalo', value: 'Gorontalo' },
  { label: 'Jakarta', value: 'Jakarta' },
  { label: 'Jambi', value: 'Jambi' },
  { label: 'Lampung', value: 'Lampung' },
  { label: 'Maluku', value: 'Maluku' },
  { label: 'North Kalimantan', value: 'North Kalimantan' },
  { label: 'North Maluku', value: 'North Maluku' },
  { label: 'North Sulawesi', value: 'North Sulawesi' },
  { label: 'North Sumatra', value: 'North Sumatra' },
  { label: 'Papua', value: 'Papua' },
  { label: 'Riau', value: 'Riau' },
  { label: 'Riau Islands', value: 'Riau Islands' },
  { label: 'Southeast Sulawesi', value: 'Southeast Sulawesi' },
  { label: 'South Kalimantan', value: 'South Kalimantan' },
  { label: 'South Sulawesi', value: 'South Sulawesi' },
  { label: 'South Sumatra', value: 'South Sumatra' },
  { label: 'West Java', value: 'West Java' },
  { label: 'West Kalimantan', value: 'West Kalimantan' },
  { label: 'West Nusa Tenggara', value: 'West Nusa Tenggara' },
  { label: 'West Papua', value: 'West Papua' },
  { label: 'West Sulawesi', value: 'West Sulawesi' },
  { label: 'West Sumatra', value: 'West Sumatra' },
  { label: 'Special Region of Yogyakarta', value: 'Special Region of Yogyakarta' },
  { label: 'Highland Papua', value: 'Highland Papua' },
  {label : 'South Papua', value: 'South Papua' },
  { label: 'Southwest Papua', value: 'Southwest Papua' },
  { label: 'Central Papua', value: 'Central Papua' }
];

export type ProvinceToPhotoMap = Record<string, string>;

export const provinceToPhotoMap: ProvinceToPhotoMap = {
  'Aceh': 'Aceh.jpg',
  'Bali': 'Bali.jpg',
  'Bangka Belitung Islands': 'BangaBelitung.jpg',
  'Banten': 'Banten.jpg',
  'Bengkulu': 'Bengkulu.jpg',
  'Special Region of Yogyakarta': 'DIYogyakarta.jpg',
  'Jakarta': 'DKIJakarta.jpg',
  'Gorontalo': 'Gorontalo.jpg',
  'Jambi': 'Jambi.jpg',
  'West Java': 'JawaBarat.jpg',
  'Central Java': 'JawaTengah.jpg',
  'East Java': 'JawaTimur.jpg',
  'West Kalimantan': 'Kalbar.jpg',
  'South Kalimantan': 'Kalsel.jpg',
  'North Kalimantan': 'Kaltara.jpg',
  'Central Kalimantan': 'Kalteng.jpg',
  'East Kalimantan': 'Kaltim.jpg',
  'Riau Islands': 'Kepulauan Riau.png',
  'Lampung': 'Lampung.jpg',
  'North Maluku': 'Maltara.jpg',
  'Maluku': 'Maluku.jpg',
  'West Nusa Tenggara': 'NTB.jpg',
  'East Nusa Tenggara': 'NTT.jpg',
  'Papua': 'Papua.jpg',
  'West Papua': 'PapuaBarat.jpg',
  'Southwest Papua': 'PapuaBaratDaya.jpg',
  'Highland Papua': 'PapuaPegunungan.jpg',
  'South Papua': 'PapuaSelatan.jpg',
  'Central Papua': 'PapuaTengah.jpg',
  'Riau': 'Riau.jpg',
  'West Sulawesi': 'Sulbar.jpg',
  'South Sulawesi': 'Sulsel.jpg',
  'North Sulawesi': 'Sultara.jpg',
  'Central Sulawesi': 'Sulteng.jpg',
  'Southeast Sulawesi': 'Sultenggara.jpg',
  'South Sumatra': 'SumateraSelatan.jpg',
  'West Sumatra': 'SumatraBarat.jpg',
  'North Sumatra': 'SumatraUtara.jpg',
};